### ISSUE TITLE
new api url's?

### ISSUE THREAD

**Issue by rduivenvoorde** [gboudreau/nissan-connect-php#10]
Hi, 

Thanks for you work, I've used it to create a small 'batterystatus' cli for myself last months.

Recently it stopped working (as the Android 'Leaf Manager' app), raising a 404....

BUT the 'leaf manager' app apparently started working again:

I see the author of the app talking here:

http://www.mynissanleaf.com/viewtopic.php?f=31&t=2214&sid=0735bb59ec930c8b6f2e95cb6f308e3b&start=120

fyi, the app I mean; https://play.google.com/store/apps/details?id=no.darkspawns.leafmanager

this python api also fixed stuff apparently: https://github.com/jdhorne/pycarwings2/commits/master

If I find time, i'll see if I can have a look into this too, but my php is  a little rusty :-)

**Comment by gboudreau** [comment]
My install doesn't have any issue. I tried climate control ON then OFF, and status update, and everything worked as expected.
Could you give me an example of what you are running, and the result / error you get?

**Comment by gboudreau** [comment]
Can you check what base URL you have, in your [NissanConnect.class.php, line 47](https://github.com/gboudreau/nissan-connect-php/blob/master/NissanConnect.class.php#L47)?
The latest class is using `https://gdcportalgw.its-mo.com/gworchest_0323C/gdc/` which still seems to work fine. Maybe you are using an older version of the class, where I had an earlier version of the base URL, maybe `gworchest_0307C`?
Try the latest class from the repo; it should work.

**Comment by rduivenvoorde** [comment]
@gboudreau ah yep, sorry. Me bad. It just works! Thanks.

PS I'm also looking that this python lib: https://github.com/jdhorne/pycarwings2
