### ISSUE TITLE
Missing RemoteACRecords

### ISSUE THREAD

**Issue by Raiden38** [gboudreau/nissan-connect-php#11]
Since April 4th, I get this error when pulling status: Missing 'RemoteACRecords' in response received in call to 'RemoteACRecordsRequest.php': {"status":200}

**Comment by gboudreau** [comment]
Yes, I'm getting the same thing.
I verified with the latest Android app, and it does the same request, and receives the same empty response. And when I try to control climate control, it fails, and tells me to try to logout and re-login, which doesn't help, so there must be something wrong at the server level.

**Comment by gboudreau** [comment]
In the commit above, I made a temporary workaround. It allows us to still use the API, even if the climate control data and controls will not work.

**Comment by Raiden38** [comment]
Merci!!!! :)

**Comment by cedric222** [comment]
I did not have the problem myself, but many users in France seems have it ! (jeedom plugin using your lib)
thanks for them !

**Comment by gboudreau** [comment]
Resolved itself by now.
