### ISSUE TITLE
"status":"-2010","message":"INVALID PARAMS"

### ISSUE THREAD

**Issue by gerfur1** [gboudreau/nissan-connect-php#12]
I have a Problem with the User-Login:
An error occurred: Request for 'UserLoginRequest.php' failed. Response received: {"status":"-2010","message":"INVALID PARAMS"}
I have a Modelyear 2014 Leaf made for Austria.
Maybe there is a general Issue?

**Comment by gboudreau** [comment]
Works for me.
You sure you specified the `NissanConnect::COUNTRY_EU` country (3rd param of the constructor)?

eg.
```
require_once 'NissanConnect.class.php';
$nissanConnect = new NissanConnect($username, $password, $tz, NissanConnect::COUNTRY_EU);
$nissanConnect->debug = TRUE;
$result = $nissanConnect->getStatus();
var_dump($result);
```

**Comment by gerfur1** [comment]
I found out why, i used Mail-Adress (as i saw in the Example) instead of my username... BTW, ther is also an alternative Base-Url: https://gdcportalgw.its-mo.com/gworchest_160803EC/gdc/
