### ISSUE TITLE
Base URL Changed Again?

### ISSUE THREAD

**Issue by jeremyakers** [gboudreau/nissan-connect-php#18]
The current Base URL of:

https://gdcportalgw.its-mo.com/gworchest_160803A/gdc/

Is returning this error message:

Http Status: 404: Not Found: 
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /gworchest_160803A/gdc/UserLoginRequest.php was not found on this server.</p>
</body></html>

Did they change the base URL again or is this a temporary issue?

-Jeremy

**Comment by gboudreau** [comment]
`Nissan LEAF` official app on Android never loads, so I guess the issue is temporary.

**Comment by windsorsean** [comment]
I just switched my scripts over to the new NissanConnect APIs. E.g. https://gist.github.com/BenWoodford/141ca350445e994e69a70aabfb6db942

**Comment by gboudreau** [comment]
There you go. Back to working. We're missing a few things, but otherwise seems to work fine.
A lot of things got deprecated...
