### ISSUE TITLE
Issue with last Commit

### ISSUE THREAD

**Issue by Raiden38** [gboudreau/nissan-connect-php#19]
With the last update, I get this issue: `Request for 'battery/vehicles/1N4AZ0CP8FC30XXXX/getChargingStatusRequest' failed. Response received: "<html><head><title>JBoss Web\/7.4.10.Final-redhat-1 - JBWEB000064: Error report<\/title><style><!--H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} P {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;}A {color : black;}A.name {color : black;}HR {color : #525D76;}--><\/style> <\/head><body><h1>JBWEB000065: HTTP Status 405 - <\/h1><HR size=\"1\" noshade=\"noshade\"><p><b>JBWEB000309: type<\/b> JBWEB000067: Status report<\/p><p><b>JBWEB000068: message<\/b> <u><\/u><\/p><p><b>JBWEB000069: description<\/b> <u>JBWEB000125: The specified HTTP method is not allowed for the requested resource.<\/u><\/p><HR size=\"1\" noshade=\"noshade\"><h3>JBoss Web\/7.4.10.Final-redhat-1<\/h3><\/body><\/html>"`

**Comment by gboudreau** [comment]
The new API seems to be having issues this morning. I get `500 Internal Server Error` errors myself. And #20 is also having issues. We'll need to wait for the API to stabilize.
Apparently, the official Nissan LEAF app on mobile is also experiencing issues.

**Comment by gboudreau** [comment]
It seems to work fine for me now. If you still have issues, post example PHP code, and output of the script running, with debugging enabled: `$nissanConnect->debug = TRUE;`

**Comment by Raiden38** [comment]
No luck for me, still get the same exact message... will check the logs and report back...

**Comment by gboudreau** [comment]
Try to delete the json file used to store credentials, and try again.
I think this issue occurs if you have that file, but the auth data in it is somehow invalid; the server would then return a 405 error instead of a 401.

**Comment by Raiden38** [comment]
Hi The last commit has resolved the issue for me! Thanks so much! :)

**Comment by gboudreau** [comment]
Fixed in 7f2fd063e0d07b790b09c081cfd175d0edb42d5d
