### ISSUE TITLE
Nissan changed api again

### ISSUE THREAD

**Issue by reulnl** [gboudreau/nissan-connect-php#28]
It looks like Nissan changed their API (or API URL) again. Within the European Nissan EV app they are now stating that a new version of the app is available and the old app has stopped working by July 29th.

Does anyone know the new API configuration so this PHP class can be updated as well?

**Comment by gboudreau** [comment]
Old API seems to still work fine for me in Canada. (NissanConnectEV official app on Android still works too.)
So I guess this would be an issue for EU users only..?

**Comment by Daxziz** [comment]
I get 404 when trying with the 3rd party applications I've got. The API has indeed been changed. All I can see is, that they're still talking to the same domain, but I can't get the actual URLs that's being used.

**Comment by SDeath667** [comment]
Here you can see the new endpoints for EU: https://gitlab.com/tobiaswkjeldsen/dartcarwings/issues/15

**Comment by gboudreau** [comment]
The changes implemented in dartcarwings don't work for me.
Request to InitialApp_v2.php works, but request to UserLoginRequest.php fails with:
```
{"status":"-2010","message":"INVALID PARAMS","resultKey":""}
```

**Comment by gboudreau** [comment]
I pushed the change in the master branch; try it yourselves, see if it works.
In Canada, those gdcportalgw.its-mo.com URLs stopped working a while ago. I'm myself using the [new-api branch](https://github.com/gboudreau/nissan-connect-php/tree/new-api), which uses a completely different API, but I guess it works only for Americans accounts.

**Comment by howartp84** [comment]
Guillaime,

I’m getting the -2010 error as well.

Mine is a UK 2019 car, which uses a different app and api; I suspect that the -2010 error is that we’re using wrong api for that account.

**Comment by SDeath667** [comment]
I updated and all is working again on my 2014 Leaf in the EU.

**Comment by reulnl** [comment]
Also for me this updated API is working, thanks!
