### ISSUE TITLE
The return of the BlahBlah code :(

### ISSUE THREAD

**Issue by Raiden38** [gboudreau/nissan-connect-php#36]
So the issue starts again today (the query worked fine this morning, but not this evening):
Non-JSON response received for request to 'POST https://icm.infinitiusa.com/NissanEVProd/rest/auth/authenticationForAAS'. Response received: BlahBlah

_Originally posted by @gboudreau in https://github.com/gboudreau/nissan-connect-php/issues/35#issuecomment-922489498_

**Comment by gboudreau** [comment]
Indeed. And I can't trace the HTTPS connection from the app now; maybe they added certificate pinning in the app, which prevents SSL proxying..?

**Comment by gboudreau** [comment]
Found new infos to use here : https://github.com/Tobiaswk/dartnissanconnectna/commit/411d5266f98d89903598ab2af6ab7c6b3e5b5650

**Comment by Raiden38** [comment]
Thanks again for your help, new version works perfectly now! :)

**Comment by gboudreau** [comment]
Broke again a few weeks ago.
Ref: https://tobis.dk/blog/open-letter-nissan-resistance-is-futile/
How to fix: https://github.com/Tobiaswk/dartnissanconnectna/commits/master
