### ISSUE TITLE
Here we go again! :)

### ISSUE THREAD

**Issue by Raiden38** [gboudreau/nissan-connect-php#38]
It's this time of year where they change everything and it does not work anymore! So any request will result in a Unauthorised request. I guess they changed the API authentification process or key... Anyways, if you can update your api with the new authentification code, if available, would be awesome!

Thanks again! 

Steven

**Comment by gboudreau** [comment]
I tried using the latest values from https://github.com/Tobiaswk/dartnissanconnectna/commits/master
(updated Api-Key header, new User-Agent-Key header)
No luck.

**Comment by gboudreau** [comment]
meh
https://gist.github.com/BenWoodford/141ca350445e994e69a70aabfb6db942#gistcomment-4044411

**Comment by Raiden38** [comment]
Not good news 😟

**Comment by gboudreau** [comment]
Working again, thanks to https://github.com/Tobiaswk/dartnissanconnectna/commits/master
