### ISSUE TITLE
Don't wait for results when sending "Charge On"

### ISSUE THREAD

**Issue by Raiden38** [gboudreau/nissan-connect-php#5]
Is there a way to send the startCharge function without waiting for an answer, just like the Climate Control? Just to avoid timeouts?

Perhaps that would make sense?

    public function startCharge($waitForResult=FALSE) {
        $this->prepare();
        $result = $this->sendRequest('BatteryRemoteChargingRequest.php');
        if ($waitForResult) {
            // Wait until it completes
            return $result;
        }
    }

Thanks!

**Comment by gboudreau** [comment]
The startCharge command is already async. If it takes time to complete, it's just the server taking its time acknowledging it received our request. Not much we can do about that.
