### ISSUE TITLE
Getting more information from Carwings

### ISSUE THREAD

**Issue by Raiden38** [gboudreau/nissan-connect-php#9]
Hi!
This is not an issue.

When you use Nissan Connect, you can get alot of stats from the car (driving km, consumption, etc etc.). Do you think there would be a way to get this information? This way, we could automaticaly builld our own stats page. Thanks!

**Comment by gerfur1** [comment]
Download Fiddler, configure it to allow remote connections, export certificate from IE and install on Smartphone, configure smartphone to use proxy and you get all communication logged.

**Comment by Raiden38** [comment]
You can probably close this one, as there is no other infos available without any massive rewrite and other connexions. Thanks for looking it out.
